### ISSUE TITLE
Error with search.py

### ISSUE THREAD

**Issue by blockbandit** [takutolehr/mctracker#1]
Came across this error today when executing search.py

./search.py -l 1650 23841 66 20424 23894 87 2050
Traceback (most recent call last):
  File "./search.py", line 206, in <module>
    search((args.x1, args.x2), (args.y1, args.y2), (args.z1, args.z2), args.items, args.disp_inventory, args.disable_api, args.name_or_uuid, args.include_enderchest, args.last_snapshots_limit)
  File "./search.py", line 140, in search
    xyz = extract_positions(data)
  File "./search.py", line 46, in extract_positions
    return fmt.unpack(xyz) 
struct.error: unpack requires a string argument of length 24

**Comment by takutolehr** [comment]
Thanks for the bug report. I will look into it.
